name: weather_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0-326.0.dev

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^3.0.0
  lottie: ^2.0.0
  loading_animation_widget: ^1.3.0
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons: ^0.9.2
  flutter_dotenv: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: any
  mocktail: ^1.0.4



flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png" 

flutter:

  uses-material-design: true
  assets:
  - assets/images/cloud.jpg
  - assets/images/rain.png
  - assets/images/thunder.jpg
  - assets/images/sun.png
  - assets/images/app_icon.png
  - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf


